# For this project, we use ReadTheDocs only for Pull Request previews. GitHub
# pages currently hosts the actual website.
version: 2


build:
  os: "ubuntu-lts-latest"
  tools:
    nodejs: "22"
  jobs:
    post_install:
      - "npm install -g mystmd"
    build:
      html:
        - "myst build --strict --html"
        - "mkdir --parents $READTHEDOCS_OUTPUT"
        - "mv ./_build/html ${READTHEDOCS_OUTPUT}/."
        - "ls -la ${READTHEDOCS_OUTPUT}/html"
        - "rm -rf _build"  # RTD build fails if _build/html is detected :(
