[workspace]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "team-compass"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]
render = "myst build --strict --html"
preview = "myst start"

[dependencies]
mystmd = ">=1.6.0,<2"
