[workspace]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "team-compass"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks.render]
cmd = "myst build --strict --html"
env = {HOST = "127.0.0.1"}

[tasks.preview]
cmd = "myst start"

[dependencies]
mystmd = "==1.6.2"
pandas = ">=2.3.1,<3"
pyyaml = ">=6.0.2,<7"
feedgen = ">=1.0.0,<2"
